### PR TITLE
Fix wav saving

### LINKED ISSUE #53: play() not working on Xiaomi devices
I have tested these functions on several devices that are Redmi Note 7, Redmi Y1, Vivo V5 and iPhone6.
I found that audio recording feature works fine. The recorded audio file is being stored as well. But player function is not working on Redmi note 7 and Redmi Y1. On other devices, it works well. 
The code is same as stated in the sample application.

Thank you.

### PR DESCRIPTION
**Pull request by mattiascibien**
This PR fixes wav saving as the original code overwrites the initial bytes of audio. Also fixes #53 as some platform enforces correctness of wav files when playing them

### CODE REVIEW

**Review by OmPals — APPROVED** [review]

**Review by LucasEGomes — APPROVED** [review]
Tested in Redmi Note 8 and worked.

**Comment by ghost** [comment]
Tested on a couple Xiaomis and it's working

**Comment by Haarmees** [comment]
Nice fix! Do you think it would be an idea/possible to write 44 "filler" bytes (size of wavheader) to the filestream in the beginning and overwrite those in the end? This would avoid using a memorystream, which could potentially create a memory problem with longer recordings.

**Comment by mattiascibien** [comment]
> Nice fix! Do you think it would be an idea/possible to write 44 "filler" bytes (size of wavheader) to the filestream in the beginning and overwrite those in the end? This would avoid using a memorystream, which could potentially create a memory problem with longer recordings.

**Pull request closed without merging**
